site:
  title: OpenShift Virtualization cookbook
  start_page: ocp-virt-cookbook_ja-1::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
