= OpenShift ビジュアライゼーション API コンポーネントの概要
:navtitle: API コンポーネントの概要

注: テストされた OpenShift バージョン: v4.19, v4.20

重要: この参照ガイドは、OpenShift ビジュアライゼーション API コンポーネントに関する概要を提供し、これらのコンポーネントとプラットフォームの全体的なアーキテクチャに関する最も重要な情報をカバーします。
これは完全な API 参照ではなく、新しい API 開発者向けのクイックスタートガイドです。

新規ユーザーまたは他の仮想化プラットフォームからのユーザーの場合、OpenShift ビジュアライゼーションは https://kubevirt.io[KubeVirt] の上流プロジェクトに基づいており、OpenShift (Kubernetes に基づく) アーキテクチャの上に構築されています。
OpenShift (および Kubernetes) のアーキテクチャは、API オブジェクトによって定義された宣言型設計を使用し、json または yaml 形式で表現できます。
OpenShift ビジュアライゼーションは、これらの宣言型 API を拡張して仮想化用の特定のオブジェクトを追加します。新規ユーザーの場合、これらのオブジェクトの役割および彼らの間の関係が混乱する可能性があります。

このガイドは、通常のアーキテクチャガイドと API ガイドをマージし、各 API コンポーネント (オブジェクトまたはリソースとも呼ばれます) の役割およびコンポーネント間の関係を明確にし、各コンポーネントの API 固有の詳細を触れています。

したがって、完全な yaml 例とスキーマは、特定のオブジェクトのサンプルと、そのオブジェクトの最も重要なフィールドのサブセット (ドット記法) を使用して避けられます。
詳細な例については、https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/virtualization/index[OpenShift ビジュアライゼーション,window=_blank] と https://kubevirt.io/user-guide/[KubeVirt,window=_blank] を参照してください。完全な API スキーマについては、https://kubevirt.io/api-reference/main/index.html[KubeVirt API リファレンス,window=_blank] を参照してください。

以下の内容がカバーされています:

* <<virtualization_apis,仮想化 API>>
** <<virtual_machines,仮想マシン>>
** <<virtual_machine_instances,仮想マシンインスタンス>>
** <<instance_types,インスタンスタイプ>>
** <<vm_cluster_instance_types,仮想マシンクラスターインスタンスタイプ>>
** <<vm_instance_types,仮想マシンインスタンスタイプ>>
** <<virtual_machine_preferences,仮想マシンおよび仮想マシンクラスタープレファレンスおよび仮想マシンプレファレンス>>
** <<preferred_cpu_topology,優先CPUトポロジー>>
** <<vcpu_spread_options,vCPU スプレッドオプション>>
* <<networking_apis,ネットワーキング API>>
** <<networks,ネットワーク>>
** <<interfaces,インターフェース>>
** <<default_network,デフォルトネットワーク>>
** <<multus_cni_plugin,Multus CNI プラグイン>>
** <<nmstate_operator,NMState オペレーター>>
* <<storage_apis,ストレージ API>>
** <<persistent_volumes,永続ボリューム>>
** <<persistent_volume_claims,永続ボリューム要求>>
** <<volume_snapshots,ボリュームスナップショット>>
** <<data_volumes,データボリューム>>
** <<data_sources,データソース>>
** <<storage_classes,ストレージクラス>>
** <<virtual_machine_snapshots,仮想マシンスナップショット>>
** <<virtual_machine_restores,仮想マシン復元>>
* <<clone_api,クローン API>>
** <<virtual_machine_clones,仮想マシンクローン>>
** <<mutating_vm_clones,クローンされた仮想マシンの変更>>
** <<patching_vm_clones,クローンされた仮想マシンのパッチング>>
** <<vm_cloning_strategies,クローン戦略およびストレージプロファイル>>
* <<export_api,エクスポート API>>
** <<virtual_machine_exports,仮想マシンエクスポート>>

== 仮想化 API [[virtualization_apis]]

=== 仮想マシン [[virtual_machines]]

仮想マシンは、API オブジェクト (テクニカルに Kubernetes カスタムリソース) で、OpenShift ビジュアライゼーションで非実行中の仮想マシンを表します。

仮想マシンには、仮想マシンインスタンス (次のセクションで説明) のテンプレートが含まれており、仮想マシンの実行状態を Status 部分で反映します。

仮想マシンの `spec` 内のさまざまなフィールドで、VM の詳細を定義します。これらのフィールドのいくつかは次のとおりです:

* `instanceType` - 仮想マシンに使用するインスタンスタイプ (RAM と CPU の割り当てに基づいてサイズ付き) の名前です。
* `volumes` - VM にアタッチされる仮想ディスクとしてリストされるボリュームのリストです。このフィールドは、https://kubevirt.io/user-guide/storage/disks_and_volumes/#volumes[さまざまなボリュームタイプをサポートします。window=_blank]、しかし、`dataVolume` と `persistentVolumeClaims` は最も一般的です。
** `dataVolume` - プロビジョニングされるデータボリュームの名前を示します。データボリュームを作成するデータボリュームテンプレートは、`dataVolumeTemplates` セクションで定義されます。
** `persistentVolumeClaim` - VM に永続ボリューム要求 (PVC) をアタッチし、ディスクとして使用します。
* `networks` - VM にバインドされるネットワークのリストです。空のフィールドはデフォルトの Pod/VM ネットワークを取得します。
* `interfaces` - VM にアタッチされるインターフェースのリストです。インターフェースは仮想 NIC を表し、Pod/VM を特定のネットワークに接続するために使用されます。
* `dataVolumeTemplates` - 作成されるデータボリュームマニフェストのリストです。`volumes` 内で参照されるように、このリストにリストされているすべてのデータボリュームを参照する必要があります。

仮想マシンの実行状態は通常、`spec.runStrategy` フィールドを使用して管理されます。これは以下の値を受け入れます:

* **Always** - デフォルトで電源がオン状態に設定され、VM が停止された場合 (手動でシャットダウンされたか、クラッシュした場合) に再起動します。
* **RerunOnFailure** - Always と同様ですが、クラッシュした場合にのみ VM を再起動します。スケジュールされたまたは手動でゲスト内からシャットダウンされた場合には再起動しません。
* **Once** - VM が 1 回のみ起動され、停止または手動でシャットダウンされた場合に再起動されません。
* **Manual** - 実行状態は自動的に管理されず、VM に POST された電源コマンドにのみ応答します。
* **Halted** - VM を停止し、`spec.runStrategy` が変更されるか、`VM に start コマンドが発行されるまで (以下で説明します) まで停止します。

注: `spec.running` フィールドは、`spec.runStrategy` フィールドの代わりに非推奨であり、排他的です。

`virtctl` コマンドは、`start`、`stop`、`restart` コマンドを発行して、仮想マシンの status サブリソース (KubeVirt が VM の現在の状態を反映するために使用する API エンドポイント) を影響することもできます。

各コマンドが発行されると、仮想マシンに対して影響を与える可能性があります:

* **start** - VM を開始し、`Halted` 実行状態を `Always` に戻します。`RerunOnFailure` または `Manual` 実行状態には影響しません。
* **restart** - 実行中の状態で VM を再起動しますが、実行状態を変更しません。`Halted` VM の場合にはノーオペレーションです。
* **stop** - VM を停止し、`Always` 実行状態を `Halted` に戻します。`RerunOnFailure` または `Manual` 実行状態には影響しません。

API レベルで、仮想マシンに対して電源コマンドが発行されると、`stateChangeRequests[]` リストが仮想マシンの status サブリソースに追加されます:

[source,yaml]
----
status:
  stateChangeRequests:
  - action: <Stop|Start> <1>
    uid: <uid-of-the-virtual-machine-instance> <2>
----
<1> 要求されるアクションの値。`Stop` または `Start` のいずれかの文字列値です。
<2> オプションの仮想マシンインスタンス (仮想マシンではなく) の UID。このフィールドは、`Start` コマンドの場合には必要ありません。VM が開始されると VMI が作成されるためです。

仮想マシンの現在の実行状態を反映する VM `status` 内の複数のフィールドがあります:

* **status.printableStatus** - VM の電源状態を簡単に確認するための最も単純なフィールドです。`Running` (開始/準備完了)、`Starting` (進行中/ブート中)、`Stopped` 状態を反映します。
* **status.runStrategy** - アクティブな実行戦略を反映し、`spec.runStrategy` フィールドおよび同じ値 (`Always`、`RerunOnFailure`、`Once`、`Manual`、`Halted`) を反映します。
* **status.conditions["type": "Ready"]** - `conditions` は、`Ready` (この場合) の文字列値を持つオブジェクトのリストを受け入れます。`status` - 布尔値、`Reason` と `Message` - オプションの理由コードと説明です。
`Ready` 状態でない例の "条件" は以下のようになります:

[source,yaml]
----
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-status-example
spec:
  ...
status:
  conditions:
    - lastProbeTime: "2025-11-10T15:00:46Z"
      lastTransitionTime: "2025-11-10T15:00:46Z"
      message: Guest VM is not reported as running
      reason: GuestNotRunning
      status: "False"
      type: Ready
----

=== 仮想マシンインスタンス [[virtual_machine_instances]]

仮想マシンインスタンス (VMI) は、OpenShift ビジュアライゼーションで実行中の VM の現在の構成を反映します。

VMI は、Kubernetes Pod の背後にあるものです。これらの Pod は (コンテナーのグループ) で、QEMU / KVM ハイパーバイザーをホスト Pod にマウントし、VM ディスクイメージ (ルートディスクおよび追加ディスク) を PersistentVolumeClaim にマウントします。

仮想マシンに関連して、VM の yaml (json) 定義の `template` の `spec.template` 部分から、VM が開始されると VMI がスピンアウトされます。

VM を停止すると、VMI が削除され、バックエンドのストレージボリューム (DataVolume、PVC、PV) は影響を受けません。

VM を再び開始すると、VM の定義に定義されたテンプレートから新しい VMI が作成され、同じボリュームが新しい VMI にアタッチされます。

=== インスタンスタイプ [[instance_types]]

OpenShift ビジュアライゼーションでは、CPU とメモリー資源は、名前付きインスタンスタイプに基づいて決定されます。
これらのインスタンスタイプは、目的または機能セットに基づいて字母でグループ化され、数字 (例: u1) で順番付けられます。
各グループには、サイズ付き (小、中、大、xxlarge、2xlarge など) のインスタンスタイプの選択が含まれており、サイズはインスタンスの文字と数字に続きます (例: u1.xlarge)。
インスタンスのグループごとのインスタンスのスケーリング比率は、目的 (メモリー重視または CPU 重視) によって異なります。

OpenShift ビジュアライゼーションで使用可能なデフォルトのインスタンスタイプは以下の通りです:

* **ネットワーク (N)** - ネットワークインテンシブなワークロードのために使用します。DPDK エンabled ノードが必要です。1:2 の CPU/RAM 比率。
* **オーバーコミット (O)** - 完全な RAM 使用量が期待されていない場合や必要ない場合に使用します。ホストメモリーのオーバープロビジョニングを許可します。1:4 の CPU/RAM 比率。
* **コンピュート専用 (CX)** - CPU インテンシブなワークロードのために使用します。専用 CPU コア/スレッドで実行されます。1:2 の CPU/RAM 比率。
* **一般目的 (U)** - "universal" または一般的なワークロードのために使用します。ホストの共有 CPU コア/スレッドで実行されます。1:4 の CPU/RAM 比率。
* **メモリー重視 (M)** - メモリー重視のワークロードのために使用します。ホストメモリーのオーバープロビジョニングを許可しません。1:8 の CPU/RAM 比率。

上記のすべてのサイズの各インスタンスタイプは、クラスター範囲で VirtualMachineClusterInstanceType で定義されます。

=== VirtualMachineClusterInstanceTypes [[vm_cluster_instance_types]]

VirtualMachineClusterInstanceType は、クラスター範囲でインスタンスタイプを定義します。これらは、OpenShift ビジュアライゼーションで新しい VM をプロビジョニングする際にデフォルトのインスタンスタイプの選択肢として使用されます。

VirtualMachineClusterInstanceTypes は、以下のフィールドの spec をサポートします (一部のトップレベルのフィールドは省略しています):

* **annotations** - オプションのセットのアノテーションをインスタンスのタイプに適用します。
* **cpu** (必須) - このインスタンスタイプの CPU 関連の構成を定義します。
** **dedicatedCPUPlacement** - VM の vCPU をホストノードの可用な物理 CPU コア/スレッドに分離するかどうかを決定します。デフォルトは `false` です。
** **guest** (必須) - 仮想マシンに公開する vCPU の数です。デフォルトは `0` です。
** **isolateEmulatorThread** - VMI のエミュレータースレッドを追加の専用物理 CPU コア/スレッドに配置するかどうかを決定します。デフォルトは `false` です。
** **maxSockets** - ホットプラグ可能なソケットの最大数を指定します。
** **model** - VMI 内で使用する CPU モデルを指定します。デフォルトは `host-model` です。
** **numa** - ホスト NUMA 設定を構成するために使用されます。
*** **guestMappingPassthrough** - 仮想 NUMA ノード内のメモリーと CPU が別のホスト NUMA ノードに移動しないようにするゲストトポロジーを作成します。デフォルトは `{}` です。
** **realtime** - virt-launcher Pod が低遅延のために VMI を調整するように指示します (リアルタイムワークロードの場合)。オプションです。
*** **mask** - リアルタイムのために使用される vCPU のマスク表現を指定します。libvirt の表現形式と一致します (例: `"0-3,^1","1,2,3","1-2"`)。
* **gpu** - インスタンスタイプに関連付けられた GPU デバイスを定義します。
** **deviceName** - 文字列値です。デフォルトは `""` です。
** **name** (必須) - 特定のデバイスプラグインに関連付けられた GPU デバイスの名前です。デフォルトは `""` です。
** **tag** - 仮想ネットワークインターフェースアドレスをゲストに表示するために指定されたタグとアドレスを示します。
** **virtualGPUOptions** - vGPU のオプションフィールド
*** **display** - vGPU の表示オプション
**** **enabled** - vGPU のバックエンドの表示アダプターを有効にするかどうかを決定します。デフォルトは `true` です。
**** **ramFB** - ゲスト OS が実際の GPU ドライバーをロードするまでブートフレームバッファーを有効にするかどうかを決定します。
***** **enabled** - デフォルトは `true` です。
* **hostDevices** - オプションでインスタンスタイプに関連付けられたデバイスを定義します。
** **deviceName** (必須) - ホストデバイスのリソース名です。デフォルトは `""` です。
** **name** (必須) - デフォルトは `""` です。
** **tag** - 仮想インターフェースアドレスをゲストに表示するために指定されたタグとアドレスです。
* **memory** (必須) - このインスタンスタイプのメモリー関連の構成を定義します。
** **guest** (必須) - 仮想ゲスト OS に公開するメモリー量 (例: `"4096Mi"` または `"6Gi"`) です。
** **hugepages** - VMI で大きなページを使用するように許可します (通常のメモリーを使用)。
*** **pageSize** - 許可される大きなページサイズを指定します。amd64 アーキテクチャーでは、`1Gi` と `2Mi` が有効です。
** **maxGuest** - 仮想ゲスト内で可視な最大メモリー量を指定します。`maxGuest` と `guest` の差はホットプラグ可能なメモリー量です。
** **overcommitPercent** - 仮想ゲストメモリーがオーバーコミットされる割合 (または virt-launcher Pod が必要とするメモリー削減率) を指定します。デフォルトは `0` です。
* **nodeSelector** - このインスタンスタイプをスケジュールする目的のノードを選択するための Kubernetes セレクターラベルです。
** **schedulerName** - インスタンスタイプのカスタム Kubernetes スケジューラーを指定します。空の場合、デフォルトの K8s スケジューラーを使用します。

=== VirtualMachineInstanceTypes [[vm_instance_types]]

VirtualMachineInstanceType は、VirtualMachineClusterInstanceType と同様ですが、名前空間範囲でのものです (クラスター範囲ではありません)。これは、OpenShift ビジュアライゼーションのウェブコンソールで VirtualMachine の `spec.instancetype` フィールドが必要であるため、ユーザー (クラスター管理者以外) が自分のプロジェクト/名前空間にアクセスできるように、自分自身のカスタムインスタンスタイプを定義できるようにします。

重要: VirtualMachine に使用するインスタンスタイプを選択するか、または定義する (CPU とメモリー構成を手動で指定する) ことは避けてください。VirtualMachineInstance の `spec.instancetype` フィールドは、OpenShift ビジュアライゼーションのウェブコンソールで必須です。これは、VirtualMachineInstance の `spec.template.spec.domain.cpu` または `spec.template.spec.domain.memory` が設定されている場合、設定できません。これは、VirtualMachineInstance の `spec.instancetype` フィールドが VirtualMachine の開始時に `spec.template.spec.domain.cpu` と `spec.template.spec.domain.memory` を設定するためです。

=== 仮想マシンおよび仮想マシンクラスタープレファレンスおよび仮想マシンプレファレンス [[virtual_machine_preferences]]

VirtualMachinePreference は、インスタンスタイプオブジェクトによってカバーされない他のマシン固有の設定を格納するために使用されます。しかし、これらの設定は単に "好み" であり、VirtualMachine オブジェクトを直接変更することでオーバーライドできます。

インスタンスタイプと同様に、VirtualMachineClusterPreference も同じ `spec` を受け入れますが、クラスター範囲です。OpenShift ビジュアライゼーションでは、VirtualMachineClusterPreference は特定のオペレーティングシステム (例: `fedora`、`rhel10`、`win11` など) に最適化された設定を格納するために使用されます。

以下は、EFI 起動と SecureBoot を有効にするように設定された VirtualMachineClusterPreference の例です:

[source,yaml]
----
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterPreference
metadata:
  name: rhel10-custom
spec:
  firmware:
    preferredUseEfi: true
    preferredUseSecureBoot: true
----

注: VirtualMachinePreference spec で BIOS ファームウェアを指定するには、`spec.firmware.preferredUseBios` を使用してください。SecureBoot は UEFI の独自の機能です。

=== 優先CPUトポロジー [[preferred_cpu_topology]]

VirtualMachinePreference のもう 1 つの便利な機能は、ゲスト OS に vCPU を表示する方法 (ゲストが CPU トポロジーを知ることを意味する) を調整できることです。これは、vCPU が CPU ソケット、コア、スレッドにどのように分割されるかを決定することです (ゲスト内の CPU トポロジーのみに影響を与え、ホストの CPU ソケット、コア、スレッドの割り当てに関係ありません)。

`preferredCPUTopology` のいくつかの設定オプションがあります:

* **sockets** (デフォルト) - vCPU をゲスト OS にソケットとして表示します
* **cores** - vCPU をゲスト OS にコアとして表示します
* **threads** - vCPU をゲスト OS にスレッドとして表示します
* **spread** - デフォルトでは、ソケットとコアに vCPU をスプレッドしますが、`spreadOptions` を設定することで調整できます。
* **any** - ゲストに vCPU をソケットとして割り当てし、vCPU の割り当てがこの好みに関連付けられていることを要求します (好みに関連付けられていないインスタンスタイプを定義するために使用されます)。

=== vCPU スプレッドオプション [[vcpu_spread_options]]

`preferredCPUTopology` が `spread` に設定されたとき、`spreadOptions` を使用して vCPU がコア、スレッド、ソケットにどのようにスプレッドされるかを調整できます。

`spreadOptions` は 2 つのフィールドを含みます:

* **across** - vCPU がコア、スレッド、ソケットにどのようにスプレッドされるかを定義します
* **ratio** (デフォルト: 2) - コアあたりの vCPU の数 (以下 `N` と呼びます)。

`across` の値は以下の通りです:

* **SocketsCores** (デフォルト) - 1 つのソケットあたり `N` 個のコアで vCPU をソケットにスプレッドします。
* **SocketsCoresThreads** - 1 つのソケットあたり `N` 個のコアと 2 つのスレッドあたりのコアで vCPU をソケット、コア、スレッドにスプレッドします。
* **CoresThreads** (2 つ以上の vCPU が必要) - 2 つのスレッドあたりのコアで vCPU をコアとスレッドにスプレッドしますが、強制的に行われます。

以下は、カスタム `preferredCPUTopology` を使用した VirtualMachinePreference の例です:

[source,yaml]
----
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: cpu-topology-example
spec:
  cpu:
    preferredCPUTopology: spread
    spreadOptions:
      across: SocketsCoresThreads
      ratio: 6
----

== ネットワーキング API [[networking_apis]]

このセクションでは、VirtualMachine と VirtualMachineInstance に関連するネットワーキングサブ API をカバーし、VM/VMI 外部の Multus CNI と NMState Operator も触れます。

VirtualMachine のネットワーキングの構成は、2 つの部分に分けられています (両方が相互に依存して必要であるため)。`networks` と `interfaces` です。それぞれの部分は以下のように説明します。

=== ネットワーク [[networks]]

VirtualMachine で、pod spec (`spec.template.spec`) の `networks[]` フィールドを使用してネットワークを構成します。複数のネットワークをリストすることができます (これは `[]` で示されますが、すべての Kubernetes リソースの `kind` についても名前が一意である必要があります)。各ネットワークの名前は一意でなければなりません (Kubernetes リソースの名前の同様です)。ネットワークには、VirtualMachine 内で同じ名前のインターフェースが定義されている必要があります。

各ネットワークは、`spec.template.spec.networks[]` で 2 つの異なるタイプの 1 つとして宣言する必要があります:

* *pod* - デフォルトの Kubernetes ネットワーク (主なネットワークのみを使用)
* *multus* - Multus CNI プラグインを使用すると、追加のネットワークを使用できます (主なネットワークとしても使用できます)

=== インターフェース [[interfaces]]

VirtualMachine で、インターフェースは、その VM にアタッチされた仮想ネットワークインターフェースカード (NIC) を表します。
これらのインターフェースは、ホスト Pod にあるゲスト VM によって仮想化されたアダプターとしてゲスト VM に提示されます。ゲストが `virtio` をサポートしていない場合 (例: Windows) に対して、OpenShift ビジュアライゼーションはさまざまな完全な NIC モデルをサポートします。

インターフェースは、VirtualMachine オブジェクトの `spec.domain.devices.interfaces[]` で定義され、機能するために `network` に関連付けられなければなりません。

以下は、インターフェースでサポートされるフィールドの非完全なリストです (必要なフィールドは 2 つだけです):

* **name** (必須) - `spec.template.spec.networks[]` で定義されたネットワークの名前と一致する必要があります。
* (必須) - 1 つのコアバインディングまたはネストされたネットワーク `binding` プラグインの名前を持つ 1 つのコアバインディングまたはネストされたネットワーク `binding` プラグインの名前:
** **bridge** - 名前付きネットワークに接続するために Linux ブリッジを使用します。
** **sriov** - `vfio` を使用してパススルー SR-IOV VF を使用して接続します。
** **masquerade** - NAT または IP マスカレード (nftables ルールを使用して) を使用してネットワークに接続します (egress と ingress の両方)。
** **binding** - 追加の (非コア) ネットワークバインディングプラグインの使用を許可します。
*** **name** - サポートされるネットワークバインディングプラグインの名前を持つ 1 つのサポートされるネットワークバインディングプラグインの名前 (例: `l2bridge`、`passt` (テクノロジープレビュー) など)。`l2bridge` は、VM `interface` と `network` 間に直接レイヤー 2 接続を作成します。`passt` は、Pod ネットワークと OpenShift ネットワークエコシステムとのより良い統合を提供するユーザー空間ソリューションです。
* **model** - サポートされるアダプターの名前 (10/100 アダプターを除く):
** **e1000** - Intel 82545EM PCI ギガビットイーサネットアダプターを仮想化します。
** **e1000e** - Intel 82574 PCI-E ギガビットイーサネットアダプターを仮想化します。
** **virtio** - これは、Linux ゲストでパフォーマンスを向上させるためにディスクおよびネットワークデバイスの仮想化標準です。
* **macAddress** - ゲスト内で可視な MAC アドレス
* *ports* - 仮想マシンゲストにフォワードするポートのリスト:
** **name** - 友好的なポート名
** **port** - 0 から 65535 までの整数値のポート番号
* **pciAddress** - 仮想マシン内で割り当てる PCI アドレス (例: `0000:81:00.1`)

ネットワーキングの使用例については、VM の定義時にセクションを参照してください。

=== デフォルトネットワーク [[default_network]]

これは (名前から推測できるように) OpenShift と Kubernetes で使用されるデフォルトネットワークです。
単に空の `pod: {}` ネットワークと空の `masquerade: {}` インターフェースを定義することで選択できます (以下に例を示します):

[source,yaml]
----
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: default-network-example
  namespace: my-namespace
spec:
  template:
    spec:
      domain:
        devices:
          interfaces:
          - name: default <1>
            masquerade: {} <2>
      networks:
      - name: default <1>
        pod: {} <3>
----
<1> `spec.template.spec` の `domain.devices.interfaces[]` (VM テンプレート spec の下にネストされている) に定義されたネットワークの名前は、VM テンプレート spec の `networks` 下の `name` に一致する必要があります。
<2> デフォルトネットワークは、NIC を根ネットワークに接続するために IP マスカレード (NAT) を使用します。
<3> Kubernetes Pod ネットワークを根ネットワークとして選択します。

デフォルトネットワークの利点は以下の通りです:

* OpenShift と Kubernetes のネイティブなものです。ネイティブ方法を使用して構成できます。
* Pod 間および同じノード上の同じ